### PR TITLE
Removed Duplicates in update build-all-images.sh  the docker-gen generator needs to be double checked for bugs!!

### PR DESCRIPTION
**Pull request by Eskyee**
After digging around the codebase I Removed what I think are duplicates and  a old RTL version 
Other checks needed here…  Please!!  @rockstardev ..

Also I think the docker-gen generator needs to be double checked for bugs!! as this shouldn't happen..
 
please check these!!
# Build tor
# Build monero
# Build lnd

### CODE REVIEW

**Comment by NicolasDorier** [comment]
we generator the build-all-images with the docker with https://github.com/btcpayserver/btcpayserver-docker/tree/master/contrib/DockerFileBuildHelper so you need to dig around why it is making double there.

**Comment by Eskyee** [comment]
I have a search 🔦 cheers

**Comment by rockstardev** [comment]
@esky33kubernetes you can load csproj in your IDE and then run the project in debug mode. If you don't manage to debug it on your end, drop me a message on Mattermost and we'll schedule a call.

**Comment by NicolasDorier** [comment]
I don't think those are duplicates, just different versions.

**Comment by rockstardev** [comment]
After reviewing this in detail - I think @Eskyee is right. lnd has duplicate versions - regular LDN and groestlcoin LND.

But Tor and monero have same multiple entries. RTL has one duplicate entry and then old version. Since #406 is merged and RTL was bumped to 0.9.3 in all fragments, I'll update this file as well.

**Review by rockstardev — APPROVED** [review]

**Comment by Eskyee** [comment]
thanks @rockstardev happy holidays .. We still grinding for 2021 xx Positive NRG`s

**Pull request merged**
