### PR TITLE
Fix explicit wallet file paths

### PR DESCRIPTION
**Pull request by napoly**
follow up to https://github.com/btcpayserver/btcpayserver/pull/6066

### CODE REVIEW

**Comment by napoly** [comment]
@sethforprivacy

**Comment by sethforprivacy** [comment]
Discussing in Mattermost, but AFAICT this has broken Monero installs again. Please jump into Mattermost ASAP @napoly.

**Comment by sethforprivacy** [comment]
@NicolasDorier I've confirmed personally and with a merchant that this PR broke Monero support again. Please revert ASAP, as all Monero merchants that update will have their stores broken until this is done, unfortunately.

CC @Kukks

**Comment by sethforprivacy** [comment]
This is the fix for anyone else who has issues:

```
# Open the Monero fragment
vim docker-compose-generator/docker-fragments/monero.yml

# Edit line 17
# Replace "entrypoint: monero-wallet-rpc --rpc-bind-ip=0.0.0.0 --disable-rpc-login --confirm-external-bind --rpc-bind-port=18082 --non-interactive --trusted-daemon  --daemon-address=monerod:18081 --wallet-dir=/wallet --tx-notify="/bin/sh ./scripts/notifier.sh  -X GET http://btcpayserver:49392/monerolikedaemoncallback/tx?cryptoCode=xmr&hash=%s""
# With
    entrypoint: monero-wallet-rpc --rpc-bind-ip=0.0.0.0 --disable-rpc-login --confirm-external-bind --rpc-bind-port=18082 --non-interactive --trusted-daemon  --daemon-address=monerod:18081 --wallet-file=/wallet/wallet --password-file=/wallet/password --tx-notify="/bin/sh ./scripts/notifier.sh  -X GET http://btcpayserver:49392/monerolikedaemoncallback/tx?cryptoCode=xmr&hash=%s"

# Note the difference being changing from wallet-dir back to wallet-file/password-file
# --wallet-file=/wallet/wallet --password-file=/wallet/password

# Update the Monero container
./btcpay-update.sh
```

Essentially just replacing `--wallet-dir=/wallet` on line 17 with `--wallet-file=/wallet/wallet --password-file=/wallet/password`. Once the PR is reverted you'll need to run `git restore docker-compose-generator/docker-fragments/monero.yml` before you can update BTCPay again properly.

**Comment by borisolah** [comment]
There were some errors where the wallet was active but the invoice creation crashed if XMR was included (a duplicate error) this fixed that too if anyones wondering. 

 Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "PK_AddressInvoices"

**Comment by sethforprivacy** [comment]
@Kukks  https://github.com/btcpayserver/btcpayserver-docker/pull/916

**Review by Marut722541 — APPROVED** [review]

**Review by Marut722541 — COMMENTED** [review]
-

**Pull request merged**
