### PR TITLE
Fix CentOS7 Compatibility

### PR DESCRIPTION
**Pull request by sumonst21**
fix: Installation error with docker in Centos 7

### CODE REVIEW

**Comment by NicolasDorier** [comment]
This break things on non Centos OS `git -c . rev-parse` error is
error: key does not contain a section: .

**Review by sumonst21 — COMMENTED** [review]
Haven't checked on Centos, this should work better.

**Comment by sumonst21** [comment]
@NicolasDorier Please have a look now `git rev-parse`

**Comment by NicolasDorier** [comment]
Sorry for taking so long

**Pull request merged**
