### PR TITLE
bump dash core docker image to 0.14.0

### PR DESCRIPTION
**Pull request by snogcel**
This pull request is intended to be used alongside https://github.com/btcpayserver/dockerfile-deps/pull/8

### CODE REVIEW

**Comment by snogcel** [comment]
@Kukks I've updated build-all-images.sh as requested, please let me know if there's anything else that needs adjustment.

**Comment by NicolasDorier** [comment]
you don't have to run the script, I run it myself time to time.

**Comment by asadaddy** [comment]
PLease merge, we would really like to use dash 0.14

**Comment by NicolasDorier** [comment]
@asadaddy this should be 0.14.0.1 but @snogcel did not updated yet.

**Comment by snogcel** [comment]
@NicolasDorier thanks for merging https://github.com/btcpayserver/dockerfile-deps/pull/8. I'll close this PR and create a new one for 0.14.0.1

**Pull request closed without merging**
