### PR TITLE
Bump RTL

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by Kukks** [comment]
Tested to be working with clightning. I'm guessing it should work fine for LND @NicolasDorier

**Comment by NicolasDorier** [comment]
reverted

```
Error: Error:
Node Authentication can be set with multiPass only. Please set multiPass in RTL-Config.json
    at Object.connect.setServerConfiguration (/RTL/connect.js:509:11)
    at Object.<anonymous> (/RTL/rtl.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by Kukks** [comment]
Ping @saubyk

**Comment by ShahanaFarooqui** [comment]
the above error message does not exist in the code after 6.5. Can you please verify if the rtl pull has pull the latest version..

**Comment by ShahanaFarooqui** [comment]
Wait a second, I found the code..let me check the issue now..

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier This issue is related to https://github.com/Ride-The-Lightning/RTL/issues/264. But, just to double check, it will be better to test it with the same RTL.conf which is being used for 0.5.4 at your end. Can you please share the contents of your RTL.conf?

**Comment by NicolasDorier** [comment]
I have 2 files, 

RTL.conf
```
[Authentication]
macaroonPath=
nodeAuthType=DEFAULT
lndConfigPath=
rtlPass=

[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
lndServerUrl=https://localhost:8080/v1
bitcoindConfigPath=
enableLogging=false
port=3000
reverseProxy=0
```
RTL-Config.json
```
{
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": "0",
    "rtlCookiePath": "",
    "logoutRedirectLink": "/login"
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "Node 1",
      "lnImplementation": "LND",
      "Authentication": {
        "macaroonPath": "",
        "configPath": ""
      },
      "Settings": {
        "userPersona": "MERCHANT",
        "enableLogging": false,
        "fiatConversion": false,
        "themeMode": "NIGHT",
        "themeColor": "INDIGO",
        "lnServerUrl": "https://localhost:8080/v1"
      }
    }
  ],
  "multiPassHashed": ""
}
```

**Comment by NicolasDorier** [comment]
Sorry for the slow response @ShahanaFarooqui

**Comment by ShahanaFarooqui** [comment]
@NicolasDorier, No problem at all. We released the next version of RTL with the fix. Please bump the version to 0.6.8 and try again.

**Comment by NicolasDorier** [comment]
All good, updated on 0.6.8, seems to work for both.

**Pull request merged**
