### PR TITLE
Add eclair for GRS and fix GRS LND

### PR DESCRIPTION
**Pull request by gruve-p**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
1. You need to `git update-index --chmod=+x` the two scripts
2. You need to modify `contrib/DockerFileBuildHelper/Program.cs`, then run the `update-repo.ps1` there, this will update the documentation with information on links of how people can build your eclair.

**Comment by gruve-p** [comment]
@NicolasDorier ready for review

**Comment by NicolasDorier** [comment]
You need to remove the chmod=+x on any other files than the two you added in this commit.

We noticed people having problem to update when permissions are changing like this. This is infortunate, but you can't fix the others now.

**Comment by NicolasDorier** [comment]
Also you need to rebase on master, because the version of other docker are not the same than on master.

**Comment by gruve-p** [comment]
@NicolasDorier Are all btcpayserver users having problems when permissions are changing or only the ones that are using grs scripts?

**Comment by pavlenex** [comment]
A few users that reported that their updates were stuck due to GRS have never used GRS.

**Comment by gruve-p** [comment]
What if we removed the faulty scripts now and added back the scripts at a later date like 3 months? Certainly there should be a solution to get the permissions right somehow?

**Comment by gruve-p** [comment]
@NicolasDorier ready for review

**Comment by NicolasDorier** [comment]
>What if we removed the faulty scripts now and added back the scripts at a later date like 3 months? Certainly there should be a solution to get the permissions right somehow?

Unsure, I don't even know how to replicate the issue.

**Pull request merged**
