### PR TITLE
Expose to clearnet using Cloudflare Argo Tunnel

### PR DESCRIPTION
**Pull request by danielcharrua**
This PR uses cloudflared for creating a tunnel to the remote machine running BTCPay Server and expose it securely to the clearnet.

First we are going to create the tunnel on Cloudflare.

You need to create an account on Cloudflare and add their DNS to your domain, in this example would be YourDomain.com.

After you've added the DNS and is propagated you can start setup of the Argo tunnel, go to ["Zero Trust"](https://dash.teams.cloudflare.com/) option on the left menu, go to "access", then click "tunnels".

Once in tunnels, you can create a new one, click "create tunnel" button. To see docs [click here](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/)
Give it a name and on the next screen "install connector" click docker and copy the string after `--token`, click next button at the bottom. You will need to input this token on an ENV variable on BTCPay setup script.

On the last screen you need to route the tunnel using your subdomain btcpay, select your domain from the list and leave path empty. Then on the service part select HTTP and then write localhost. You are going to route the subdomain traffic to http:://localhost

If you are using other port than 80 for http you can route traffic to http:://localhost:YourPort

For setup of BTCPay I've used:
```
export BTCPAY_HOST="btcpay.YourDomain.com"
export NBITCOIN_NETWORK="testnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_REVERSEPROXY="none"
export BTCPAYGEN_LIGHTNING="clightning"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="cloudflared"
export CLOUDFLARE_TUNNEL_TOKEN="YourTunnelTokenHere"
```

See that nginx reverse proxy is disabled as Cloudflare is acting as the reverse proxy and added cloudflared to BTCPAYGEN_ADDITIONAL_FRAGMENTS. Also add the tunnel token to CLOUDFLARE_TUNNEL_TOKEN.

I hope I'm not missing anything. This is a preliminar test of using tunnels to expose to clearnet. On Cloudflare you have also an option to force https on all requests.

Would need to add also documentation on this. This is just for review @NicolasDorier 
I have an error somewhere because the ENV variable is not persisted and on running the setup script again seems to erase the value of the CLOUDFLARE_TUNNEL_TOKEN. Maybe you can tell me where to add this.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@danielcharrua I think you can improve things!

The problem with your setup is that you disable the reverse proxy.
The reverse proxy is useful because it also route requests to other services that your docker install may run (for example, RTL, Lightning Terminal, Spark etc...).

If all you want is to disable HTTPS on local reverse proxy, you can try this:

```bash
BTCPAYGEN_EXCLUDE_FRAGMENTS="$BTCPAYGEN_EXCLUDE_FRAGMENTS;nginx-https"
. btcpay-setup.sh -i
```

This is similar to the trick used in this https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

**Comment by NicolasDorier** [comment]
` add their DNS to your domain, in this example would be YourDomain.com.` I am having difficulties on this step? What record should I add?

**Comment by NicolasDorier** [comment]
I see that this docker image doesn't support arm64. I think I'll create our on image in our dockerfile-deps repo

**Comment by danielcharrua** [comment]
> If all you want is to disable HTTPS on local reverse proxy, you can try this:
> 
> This is similar to the trick used in this https://docs.btcpayserver.org/FAQ/Deployment/#can-i-use-an-existing-nginx-server-as-a-reverse-proxy-with-ssl-termination

Great, will try and let you know!
did you discover that other services were affected by automated tests?

> add their DNS to your domain, in this example would be YourDomain.com.
> EDIT2: Actually is it possible without changing nameserver?

Actually I think that is possible, I have discovered because of your question https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/#how-can-tunnel-be-used-with-partial-dns-cname-setup

Great Job on adding docs, persist ENV variable and creating cross platform docker image of cloudflared @NicolasDorier

So I think that the setup would be something like:

```
export BTCPAY_HOST="btcpay.YourDomain.com"
export NBITCOIN_NETWORK="testnet"
export BTCPAYGEN_CRYPTO1="btc"
export BTCPAYGEN_REVERSEPROXY="nginx"
export BTCPAYGEN_LIGHTNING="clightning"
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="cloudflared"
export BTCPAYGEN_EXCLUDE_FRAGMENTS="$BTCPAYGEN_EXCLUDE_FRAGMENTS;nginx-https"
export CLOUDFLARE_TUNNEL_TOKEN="YourTunnelTokenHere"
```

Does this needs anything else? In the next days I will follow docs again to see if we are missing something.

**Comment by NicolasDorier** [comment]
@danielcharrua I think Always Use HTTPS shold be checked

**Comment by NicolasDorier** [comment]
Holy shit, it really just work! I tested it on my own setup at home, and it worked as advertised.

I will try it on a blank VPS as well tomorrow!

**Comment by danielcharrua** [comment]
> Holy shit, it really just work! I tested it on my own setup at home, and it worked as advertised. I will try it on a blank VPS as well tomorrow!
> 
> People will be so happy about this. I was forever searching a solution.

I was looking for the same solution months ago and trying different approaches... If this works would be a game change and add less barriers to exposing securely to clearnet.

I'm glad to help here 🤗

I have one question, why try on a VPS that is already exposed to clearnet? To add more security?

**Comment by NicolasDorier** [comment]
No reason, it's just so I can try on a brand new install making sure instructions work, and it's not thanks to some other settings I forgot to mention.

**Comment by NicolasDorier** [comment]
OK it seems ready to go now!

**Comment by danielcharrua** [comment]
> OK it seems ready to go now!
> We will make a big release today. Will mention this in the blog post.

Great news Nicolas, let me know where the blog post will be published to check it. Thank you! 💪

**Comment by danielcharrua** [comment]
@NicolasDorier maybe we need to add docs also on https://docs.btcpayserver.org/Deployment/Hardware/

Agree?

**Comment by danielcharrua** [comment]
We must also advise that the feature "Rocket Loader" in Cloudflare must be off (I think this is the default state)

I have it on on my domain as I was testing some other settings but after the woocommerce redirected to BTCPay in my subdomain a blank page was presented and on console I can see:

testpay.mydomain.es/i/UuknQ2HU46UyQaBTtmqf5x

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'nonce-fc7b3838e3d2a9692c86f4052e41cf76' 'nonce-9965b96e237455253c02e7384931f313' 'nonce-1683d602493894f6e0a233c70e923e20' 'nonce-15a7793495400de8cb374ff38f2b6094' 'nonce-35db2651c6fecb1b70221726f648fed0' 'nonce-03956b6bcf6f2c6f9b43ac94f065e342' 'nonce-b58ef9ae19618029dd159f23d585343b'". Either the 'unsafe-inline' keyword, a hash ('sha256-1Qsf2rC4vtQh6valDJ45E+bWtx+P8FH/9wdCR8XuSTU='), or a nonce ('nonce-...') is required to enable inline execution.`

Captura de Pantalla 2022-07-01 a las 10 11 44

**Pull request merged**
