### PR TITLE
Bumping LND to 0.17.4-beta-rc1

### PR DESCRIPTION
**Pull request by rockstardev**
Creating this PR to test the latest RC version of LND. There are a lot of important fixes so thus expediting with RC: https://github.com/lightningnetwork/lnd/releases/tag/v0.17.4-beta.rc1

This version also includes the ability to skip our auto initialization/unlocking of the LND wallet using `LND_SKIP_INITUNLOCK` environment variable. Once merged this will resolve the issue: https://github.com/btcpayserver/btcpayserver/issues/5612 

To test on your server connect with SSH and do:

```
git fetch
git checkout feat/lnd-v0.17.4-beta-rc1
btcpay-update.sh
```

### CODE REVIEW

**Comment by warioishere** [comment]
testing now, will give feedback later on

**Comment by AryanJ-NYC** [comment]
I was on 0.17.3 and was riddled with syncing issues.

I've pulled and updated here. Will check back in.

**Comment by rockstardev** [comment]
LND 0.17.4 has been released so I'll close this PR and open new one soon.

Thanks for testing @warioishere & @AryanJ-NYC, let me know how RC test goes.

**Comment by warioishere** [comment]
no problems so far, run stable, opened 2 channels, but i was not running pruning, but the consensus is that it fixes the pruning bug :)

**Pull request closed without merging**
