### PR TITLE
Monacoin support

### PR DESCRIPTION
**Pull request by wakiyamap**
Please let me teach if you have any problems.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
yeah, can you rebase?

**Comment by NicolasDorier** [comment]
Ping @cryptcoin-junkey I am not part of the monacoin community, can you review it? Also does @wakiyamap is a monacoin dev (to know if it is "safe" to use his image)?

**Comment by wakiyamap** [comment]
I rebase it.
If there is cryptcoin-junkey 's image, it may be better to use that.
I could not find it.

**Comment by NicolasDorier** [comment]
The source of the image is also more a question of who will better maintain it on the long term.

**Comment by wakiyamap** [comment]
I will maintain about the image of monacoin.
Should I write it somewhere?

**Comment by NicolasDorier** [comment]
Now it is merge, can you try it?

**Comment by wakiyamap** [comment]
thanks.
https://btcpay.electrum-mona.org
It working now.

**Pull request merged**
