### PR TITLE
Add RTL for C-Lightning

### PR DESCRIPTION
**Pull request by Kukks**
cc @saubyk
Fixed and ready!
~~TODO:~~
~~* change image to official one once published~~
~~* figure out why RTl crashes with~~
```
/RTL/connect.js:171
    if(config.Authentication.nodeAuthType === '' ||  undefined === config.Authentication.nodeAuthType) {
                             ^

TypeError: Cannot read property 'nodeAuthType' of undefined
    at Object.connect.validateSingleNodeConfig (/RTL/connect.js:171:30)
    at Object.connect.setSingleNodeConfiguration (/RTL/connect.js:540:13)
    at Object.connect.setServerConfiguration (/RTL/connect.js:592:13)
    at Object.<anonymous> (/RTL/rtl.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```~~

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@petzsch get the same problem with the current version it seems.

**Comment by Kukks** [comment]
I bumped to 0.6.2 and now get
```
/RTL/connect.js:254
  if (config.Settings.enableLogging) {
                      ^

TypeError: Cannot read property 'enableLogging' of undefined
    at Object.connect.validateSingleNodeConfig (/RTL/connect.js:254:23)
    at Object.connect.setSingleNodeConfiguration (/RTL/connect.js:535:13)
    at Object.connect.setServerConfiguration (/RTL/connect.js:583:13)
    at Object.<anonymous> (/RTL/rtl.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by petzsch** [comment]
I've the same problem on LND with RTL.
My RTL.conf also looks kind of weird: https://pastebin.com/Y7FNvT9U

**Comment by NicolasDorier** [comment]
My working config
```bash
docker exec generated_lnd_bitcoin_rtl_1 cat /data/RTL.conf
```
```ini
[Authentication]
macaroonPath=
nodeAuthType=DEFAULT
lndConfigPath=
rtlPass=

[SSO]
rtlSSO=0
rtlCookiePath=
logoutRedirectLink=/login
[Settings]
flgSidenavOpened=true
flgSidenavPinned=true
menu=Vertical
menuType=Regular
theme=dark-blue
satsToBTC=false
lndServerUrl=https://localhost:8080/v1
bitcoindConfigPath=
enableLogging=false
port=3000
reverseProxy=0
```

**Comment by NicolasDorier** [comment]
@petzsch you have docker deployment? your config seems strange, how did you get it?

**Comment by petzsch** [comment]
Just the regular [Docker Deployment](https://github.com/btcpayserver/btcpayserver-docker/). Selecting one crypto (BTC) and LND. Everything else was on default. I have no idea what caused it.

**Comment by Kukks** [comment]
It is fixed now in latest RTL version. C-lightning integration works! @petzsch 0.6.3 might also fix your issue 

For now using my image `kukks/clightning-rest:0.2.0` but we can change to an official one later when they set up their CI.

**Comment by petzsch** [comment]
I am now getting this in docker logs:

```
/RTL/connect.js:133
  } else if (config.Settings.lnImplementation && config.Settings.lnImplementation !== '') {
                             ^

TypeError: Cannot read property 'lnImplementation' of undefined
    at Object.connect.validateSingleNodeConfig (/RTL/connect.js:133:30)
    at Object.connect.setSingleNodeConfiguration (/RTL/connect.js:522:13)
    at Object.connect.setServerConfiguration (/RTL/connect.js:570:13)
    at Object.<anonymous> (/RTL/rtl.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

The Config still looks the same. I don't know what/where it is generated like this in the first place.

**Comment by Kukks** [comment]
> 
> 
> I am now getting this in docker logs:
> 
> ```
> /RTL/connect.js:133
>   } else if (config.Settings.lnImplementation && config.Settings.lnImplementation !== '') {
>                              ^
> 
> TypeError: Cannot read property 'lnImplementation' of undefined
>     at Object.connect.validateSingleNodeConfig (/RTL/connect.js:133:30)
>     at Object.connect.setSingleNodeConfiguration (/RTL/connect.js:522:13)
>     at Object.connect.setServerConfiguration (/RTL/connect.js:570:13)
>     at Object.<anonymous> (/RTL/rtl.js:5:36)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> ```
> 
> The Config still looks the same. I don't know what/where it is generated like this in the first place.
> 
> **EDIT:** after bumping to shahanafarooqui/rtl:0.6.3

You should ignore the config file, AFAIK it is the default version. The environment variables we pass are not reflected in the config file but take precedence

**Comment by Kukks** [comment]
@petzsch  try switching to 0.5.4

**Comment by petzsch** [comment]
I still think it's an issue with my config. Looks totally different from what @NicolasDorier posted earlier.

After downgrading to 0.5.4:

```
/RTL/connect.js:156
    if(config.Authentication.nodeAuthType === '' ||  undefined === config.Authen             tication.nodeAuthType) {
                             ^

TypeError: Cannot read property 'nodeAuthType' of undefined
    at Object.connect.validateSingleNodeConfig (/RTL/connect.js:156:30)
    at Object.connect.setSingleNodeConfiguration (/RTL/connect.js:501:13)
    at Object.connect.setServerConfiguration (/RTL/connect.js:553:13)
    at Object.<anonymous> (/RTL/rtl.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by Kukks** [comment]
try deleting it and restarting RTL

**Comment by NicolasDorier** [comment]
ping @ShahanaFarooqui and @saubyk why would RTL trash the config?

**Comment by ShahanaFarooqui** [comment]
We are already aware about the issue and working on the fix. Will inform you with the solution in 2-3 days.

**Comment by ShahanaFarooqui** [comment]
@petzsch, @NicolasDorier, @Kukks Release canditate version '0.6.4-rc' is available on docker for testing. Please delete the above weird config file (https://pastebin.com/Y7FNvT9U) before restarting the RTL server.

**Comment by ShahanaFarooqui** [comment]
Also, change the environment variable 'RTL_CONFIG_PATH' from '/***/RTL.conf' to '/***'. Environment variable RTL_CONFIG_PATH is NOT full path anymore, It is only the path for the folder containing 'RTL-Config.json' file, EXCLUDING the file name.

https://github.com/Ride-The-Lightning/RTL/releases/tag/v0.6.4-rc

**Comment by ShahanaFarooqui** [comment]
@petzsch, @NicolasDorier, @Kukks, Another RC version '0.6.4-rc1' has been deployed with an SSO authentication bug fix. Please test with this version.

**Comment by NicolasDorier** [comment]
we just bumped to 0.6.7

**Comment by Kukks** [comment]
AFAIK there was a breaking change in the config in  the latest versions so be mindful with the bump

**Comment by NicolasDorier** [comment]
Your latest bump to 0.6.1 did not show any change of config. Is that right @ShahanaFarooqui ?

**Comment by ShahanaFarooqui** [comment]
Yes, config changes were introduced from 0.6.4 onwards.

**Pull request merged**
