### PR TITLE
wip:add dash docker

### PR DESCRIPTION
**Pull request by Kukks**
Adds support for Dash. Not tested.

### CODE REVIEW

**Comment by Kukks** [comment]
Made sure it all starts up correctly and whatnot but there is some weird issue with the rpc not being able to connect. Not sure what's up with that. Maybe @bdangh can help since he seems knowledgeable in Dash? 

The logs say that Dash is syncing correctly but everytime I try to connect via cli I get "Couldn't connect to server"

**Comment by Kukks** [comment]
@snogcel Are you working on this one or you have your own image?

**Comment by snogcel** [comment]
@Kukks I created a fork of your repo and was planning to PR some changes to your feature/dash branch. The primary change is the addition of "DASH_EXTRA_ARGS" which I'm passing through to a custom version of the Uphold / Dash Docker. Would you prefer if I PR to your branch, or just create a brand new one here?

**Comment by Kukks** [comment]
Your call :)

**Comment by snogcel** [comment]
Cool sounds good :-)

Just waiting for this PR to be merged which should be the last piece of the puzzle: https://github.com/MetacoSA/NBitcoin/pull/581

**Comment by NicolasDorier** [comment]
bumped nbx, you can give another try.

**Comment by NicolasDorier** [comment]
also `git update-index --chmod=+x dash-cli.sh` and commit that.

**Comment by NicolasDorier** [comment]
also need rebase.

**Comment by snogcel** [comment]
thanks @NicolasDorier I should have this finished up early next week

**Comment by Kukks** [comment]
This pull request has been mentioned on **NBitStack**. There might be relevant details there:

https://nbitstack.com/t/dash-not-install/125/2

**Pull request merged**
