### PR TITLE
Add docker fragment for opt-txindex to enable txindex=1

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Comment by Kukks** [comment]
Also wondering if we should have a check to see if opt-save-storage is included and block installation if that's the case?

**Comment by NicolasDorier** [comment]
@Kukks yes we should, can do it in the shell script.

**Comment by wiz** [comment]
Okay I'll
1) Add documentation
2) Modify setup script to check for conflicting options

**Comment by wiz** [comment]
k

**Pull request merged**
