### PR TITLE
Expose Bitcoin RPC via Tor v3

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Still need to create a fix login/pwd.

**Comment by pavlenex** [comment]
@Fonta1n3 will be happy :-)

**Comment by ChristopherA** [comment]
Some discussion about switching to use URI of by `standup:` instead. See: https://github.com/BlockchainCommons/Bitcoin-Standup#quick-connect-url-using-btcstandup

CC: @Fonta1n3

**Comment by NicolasDorier** [comment]
I implemented using `btcrpc:` for now.

**Pull request merged**
