### PR TITLE
Add plugins dir volume to btcpay

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by Kukks** [comment]
@ndeet  this should fix the weird issue of the installed plugin disappearing between restarts

**Comment by RiccardoMasutti** [comment]
Is it possible to use it to enable c-lightning plugins like #392?

**Comment by thiagolcks** [comment]
Is there any documentation explaining how to use it to install a c-lightning plugin?

**Comment by ksdhans** [comment]
> Is it possible to use it to enable c-lightning plugins like #392?

I'd like to know this too. I've just had almost all my inbound liquidity wiped out. Some channels were closed, while others are currently disconnected. I'd very much like to use something like the clboss plugin to manage this automatically.

**Pull request merged**
