### PR TITLE
Add BTX support

### PR DESCRIPTION
**Pull request by dalijolijo**
- The docker image **docker-bitcore** v0.15.2 for Bitcore BTX you can find on [hub.docker.com](https://hub.docker.com/r/dalijolijo/docker-bitcore/tags/)

- The sources (Dockerfile and docker-entrypoint.sh) are available on [GitHub]( https://github.com/dalijolijo/btcpayserver-docker-bitcore)

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Run `git update-index --chmod=+x bitcore-cli.sh` and commit.

Make also sure that you did this on the `entrypoint.sh` of your docker image, or it will not work on linux.

**Comment by dalijolijo** [comment]
I get the following error :
```sh
$docker logs generated_nbxplorer_1
info: Configuration:  BTX: Testing RPC connection to http://bitcored:43782/
fail: Configuration:  BTX: Error connecting to RPC server The remote server returned an error: (401) Unauthorized.
fail: Configuration:  BTX: Unhandled in Waiter loop
NBXplorer.Configuration.ConfigException
   at NBXplorer.Configuration.RPCArgs.TestRPCAsync(NBXplorerNetwork networkInfo, RPCClient rpcClient, CancellationToken cancellation) in /source/NBXplorer/Configuration/RPCArgs.cs:line 134
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 259
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 197
```

@NicolasDorier Please have a look on this. Do you have an idea?

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/issues/580

**Comment by dalijolijo** [comment]
@NicolasDorier  This necessary fix https://github.com/MetacoSA/NBitcoin/pull/581 is merged but a new version of NBitcoin and NBxplorer are needed to resolve cookie issue of btcpayser-docker solution.

**Comment by NicolasDorier** [comment]
updated image

**Comment by dalijolijo** [comment]
@dalijolijo Test sucessful. 
Please merge.

**Comment by NicolasDorier** [comment]
How big the chain is?

**Comment by dalijolijo** [comment]
> How big the chain is?
current BTX chain size is 1250MB

**Comment by dalijolijo** [comment]
Which ports are required to be opened? Is only port 443 and 80 (without lightning enabled) required - or additional P2P port for selected coins?

**Comment by NicolasDorier** [comment]
other ports are for testnet.

By "how big" I mean how many blocks?

**Comment by dalijolijo** [comment]
> other ports are for testnet.
> 
> By "how big" I mean how many blocks?

See http://insight.bitcore.cc/  - about 287,900 blocks

**Comment by NicolasDorier** [comment]
I don't know why it timeout. Make sure the altcoin tests of bitcore with NBitcoin pass properly.Try to delete the docker volumes.

**Comment by dalijolijo** [comment]
image

chain is synced but status is only "node is starting"

**Comment by dalijolijo** [comment]
> I don't know why it timeout. Make sure the altcoin tests of bitcore with NBitcoin pass properly.Try to delete the docker volumes.

Do you mean Dockerfile without ```VOLUME /data``` ?

**Comment by dalijolijo** [comment]
@NicolasDorier Please have a look on these logs :

**docker logs generated_nbxplorer_1**
```sh
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTX
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTX
info: Configuration:  BTX: Testing RPC connection to http://bitcored:43782/
Hosting environment: Production
Content root path: /app/
Now listening on: http://0.0.0.0:32838
Application started. Press Ctrl+C to shut down.
info: Configuration:  BTX: RPC connection successfull
info: Configuration:  BTX: Full node version detected: 150200
info: Events:         BTX: Node state changed: NotStarted => CoreSynching
info: Configuration:  BTX: The cached chain contains a tip unknown to the node, dropping the cache...
info: Configuration:  BTX: Loading chain from node (172.27.0.3:39388)...
fail: Configuration:  BTX: Unhandled in Waiter loop
System.OperationCanceledException: Loading the chain from the node timed out
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /source/NBXplorer/BitcoinDWaiter.cs:line 376
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 302
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 197
info: Configuration:  BTX: The cached chain contains a tip unknown to the node, dropping the cache...
info: Configuration:  BTX: Loading chain from node (172.27.0.3:39388)...
fail: Configuration:  BTX: Unhandled in Waiter loop
System.OperationCanceledException: Loading the chain from the node timed out
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /source/NBXplorer/BitcoinDWaiter.cs:line 376
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 302
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 197
info: Configuration:  BTX: The cached chain contains a tip unknown to the node, dropping the cache...
info: Configuration:  BTX: Loading chain from node (172.27.0.3:39388)...
fail: Configuration:  BTX: Unhandled in Waiter loop
System.OperationCanceledException: Loading the chain from the node timed out
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /source/NBXplorer/BitcoinDWaiter.cs:line 376
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 302
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 197
info: Configuration:  BTX: The cached chain contains a tip unknown to the node, dropping the cache...
info: Configuration:  BTX: Loading chain from node (172.27.0.3:39388)...
fail: Configuration:  BTX: Unhandled in Waiter loop
System.OperationCanceledException: Loading the chain from the node timed out
   at NBXplorer.BitcoinDWaiter.ConnectToBitcoinD(CancellationToken cancellation) in /source/NBXplorer/BitcoinDWaiter.cs:line 376
   at NBXplorer.BitcoinDWaiter.StepAsync(CancellationToken token) in /source/NBXplorer/BitcoinDWaiter.cs:line 302
   at NBXplorer.BitcoinDWaiter.StartLoop(CancellationToken token, AutoResetEvent tick) in /source/NBXplorer/BitcoinDWaiter.cs:line 197
info: Configuration:  BTX: The cached chain contains a tip unknown to the node, dropping the cache...
...
```

**docker logs generated_btcpayserver_1**
```sh
info: Configuration:  Data Directory: /datadir
info: Configuration:  Configuration File: /datadir/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTX
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTX
info: Configuration:  LogFile: btcpay.log
info: Configuration:  Log Level: Debug
info: Configuration:  Root Path: /
info: Configuration:  Postgres DB used (User ID=postgres;Host=postgres;Port=5432;Database=btcpayservermainnet)
info: Hangfire.BackgroundJobServer: Starting Hangfire Server
info: Hangfire.BackgroundJobServer: Using job storage: 'Hangfire.MemoryStorage.MemoryStorage'
info: Hangfire.BackgroundJobServer: Using the following options for Hangfire Server:
info: Hangfire.BackgroundJobServer:     Worker count: 20
info: Hangfire.BackgroundJobServer:     Listening queues: 'default'
info: Hangfire.BackgroundJobServer:     Shutdown timeout: 00:00:15
info: Hangfire.BackgroundJobServer:     Schedule polling interval: 00:00:15
info: Configuration:  BTX: Explorer url is http://nbxplorer:32838/
info: Configuration:  BTX: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration:  SSH settings detected, testing connection to root@<host> on port 22 ...
info: PayServer:      Starting listening NBXplorer (BTX)
info: PayServer:      Start watching invoices
warn: Configuration:  SSH invalid credentials
info: Configuration:  Listening on http://0.0.0.0:49392
info: Events:         NBXplorer BTX: NotConnected => Synching
info: PayServer:      User logged in.
```

**btcpayserver-docker-bitcore**
image
Syncing the blockchain holds at 99%

**Comment by NicolasDorier** [comment]
I don't know why the chain is timing out. Try to delete the volume of the BTCPayServer container.  I don't know how.

**Comment by dalijolijo** [comment]
```
$docker inspect btcpayserver_bitcored
        "Mounts": [
            {
                "Type": "volume",
                "Name": "generated_bitcore_datadir",
                "Source": "/var/lib/docker/volumes/generated_bitcore_datadir/_data",
                "Destination": "/data",
```
The volume is located in /var/lib/docker/volumes/generated_bitcore_datadir/_data
The error still occurred even though I deleted the content of the volume.

**Comment by NicolasDorier** [comment]
sorry I don't know.

**Comment by dalijolijo** [comment]
@NicolasDorier found wrong Genesis Hash in NBITCOIN for mainnet.
Here is the pull request to fix it : https://github.com/MetacoSA/NBitcoin/pull/604

**Comment by dalijolijo** [comment]
@NicolasDorier 
I need new versions of NBXlorer and btcpayserver with the BTX Genesis Hash fix inside.
Here is the pull request for new NBitcoin version inside NBXplorer https://github.com/dgarage/NBXplorer/pull/140

**Comment by NicolasDorier** [comment]
I don't use docker hub build anymore, 2.0.0.2 is tagged.

**Comment by dalijolijo** [comment]
@NicolasDorier ok. Thanks. Please merge https://github.com/btcpayserver/btcpayserver/pull/430

**Comment by dalijolijo** [comment]
@NicolasDorier Ready to merge. It works fine.

image

Thanks for your support :+1:

**Comment by dalijolijo** [comment]
@NicolasDorier Please merge. Thx

**Pull request merged**
