### PR TITLE
add Zammad support system

### PR DESCRIPTION
**Pull request by xpayserver**
I try chatwoot but it slightly limited so now I try Zammad. Better setup and feature

### CODE REVIEW

**Comment by britttttk** [comment]
@xpayserver can you post the github link so we can see what zammad is?

**Comment by pavlenex** [comment]
@britttttk you can preview it on xpayserver.com it's a ticketing system. This can be useful for third-party hosts.

**Review by Kukks — APPROVED** [review]
This looks better integrated than the other one you did #353  since there are no weird custom commands you need to run to install. 

LGTM in terms of code
@pavlenex You said this is running in production already? That means we can probably merge this one

**Comment by pavlenex** [comment]
@Kukks It's running in production on https://xpayserver.com/ and they use it as a ticket support system.
There's a minor conflict in readme.md 😃

**Pull request merged**
