### PR TITLE
 add bitkarrot utxo-set signature

### PR DESCRIPTION
**Pull request by bitkarrot**
ok here goes!

### CODE REVIEW

**Comment by bitkarrot** [comment]
wen merge?

**Comment by Kukks** [comment]
@NicolasDorier I left this up to you to decide on merge since you're the master of sigs for this part

**Comment by bitkarrot** [comment]
bump

**Comment by bitkarrot** [comment]
It was all @britttttk  's idea back in July..... hope we can get this merged? :)  Lmk.

**Comment by NicolasDorier** [comment]
Sorry about that @bitkarrot , lost in my sea of notifications

**Pull request merged**
