### PR TITLE
WIP: Add btc-rpc-explorer option

### PR DESCRIPTION
**Pull request by Kukks**
cc @janoside would be good if you started publishing official images

### CODE REVIEW

**Comment by BitcoinMitchell** [comment]
Any change you/we could finish this @Kukks? This would def. be nice to have as that means that I don't have to worry about leaking data when I want to lookup some things.

**Comment by Kukks** [comment]
I forgot what the issues were. Please feel free to pick it up or maybe @maltokyo  would add another awesome fragment to his portfolio :D

**Comment by maltokyo** [comment]
Actually, I was thinking to add mempool.space - its better ;)
Shall we close this, and I will add mempool?

**Comment by Kukks** [comment]
> Actually, I was thinking to add mempool.space - its better ;)
> Shall we close this, and I will add mempool?

image

**Comment by maltokyo** [comment]
Done 
https://github.com/btcpayserver/btcpayserver-docker/pull/472

**Pull request closed without merging**
