### PR TITLE
Revert "Deleting LND volume on old installations"

### PR DESCRIPTION
**Pull request by NicolasDorier**
Reverts btcpayserver/btcpayserver-docker#340

### CODE REVIEW

**Comment by NicolasDorier** [comment]
reverting it, if the volume does not work the script will fail @rockstardev

**Comment by rockstardev** [comment]
No it won't... see the log here: https://github.com/btcpayserver/btcpayserver-docker/issues/272

And test it locally.

**Comment by rockstardev** [comment]
@NicolasDorier see it executed:

deletion successful

**Comment by NicolasDorier** [comment]
ok let's revert the revert

**Comment by NicolasDorier** [comment]
reverted the revert.

**Pull request merged**
