### PR TITLE
Bumping LND to 0.17.1-beta

### PR DESCRIPTION
**Pull request by rockstardev**
Creating this PR to prepare for updating of LND in our docker deployment.
Leaving it in draft mode so it's tested and merged as part of publishing new version.

https://github.com/btcpayserver/btcpayserver/pull/5474

To test on your server connect with SSH and do:

```
git fetch
git checkout feat/lnd-v0.17.1-beta
btcpay-update.sh
```

### CODE REVIEW

**Comment by dennisreimann** [comment]
Deployed it on the Einundzwanzig server, will report back in a few days — once the node is done restarting 🙈

```
2023-11-15 08:31:01.972 [INF] LTND: Version: 0.17.1-beta commit=basedon-v0.17.1-beta-fresh-btcpay, build=production, logging=default, debuglevel=info
2023-11-15 08:31:01.973 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2023-11-15 08:31:01.975 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2023-11-15 08:31:01.975 [INF] RPCS: RPC server listening on 127.0.0.1:10008
2023-11-15 08:31:01.975 [INF] RPCS: RPC server listening on 172.24.0.9:10009
2023-11-15 08:31:01.991 [INF] RPCS: gRPC proxy started at 172.24.0.9:8080
2023-11-15 08:31:01.991 [INF] LTND: Opening the main database, this might take a few minutes...
2023-11-15 08:31:01.991 [INF] LTND: Opening bbolt database, sync_freelist=false, auto_compact=true
2023-11-15 08:31:01.996 [INF] CHDB: Compacting database file at /root/.lnd/data/graph/mainnet/channel.db
2023-11-15 08:31:02.345 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...

[...]

2023-11-15 08:52:43.060 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
2023-11-15 08:52:43.062 [INF] CHDB: DB compaction of /root/.lnd/data/graph/mainnet/channel.db successful, 16492810240 -> 14598987776 bytes (gain=1.13x)
2023-11-15 08:52:43.065 [INF] CHDB: Swapping old DB file from /root/.lnd/data/graph/mainnet/temp-dont-use.db to /root/.lnd/data/graph/mainnet/channel.db
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-15 08:52:45.083 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-15 08:52:45.444 [INF] CHDB: Compacting database file at /root/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2023-11-15 08:52:45.467 [INF] CHDB: DB compaction of /root/.lnd/data/chain/bitcoin/mainnet/macaroons.db successful, 32768 -> 32768 bytes (gain=1.00x)
2023-11-15 08:52:45.468 [INF] CHDB: Swapping old DB file from /root/.lnd/data/chain/bitcoin/mainnet/temp-dont-use.db to /root/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2023-11-15 08:52:45.469 [INF] CHDB: Compacting database file at /root/.lnd/data/graph/mainnet/sphinxreplay.db
2023-11-15 08:52:47.103 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...

[...]

2023-11-15 08:58:10.668 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-15 08:58:12.371 [INF] CHDB: DB compaction of /root/.lnd/data/graph/mainnet/sphinxreplay.db successful, 3585683456 -> 3413393408 bytes (gain=1.05x)
2023-11-15 08:58:12.372 [INF] CHDB: Swapping old DB file from /root/.lnd/data/graph/mainnet/temp-dont-use.db to /root/.lnd/data/graph/mainnet/sphinxreplay.db
2023-11-15 08:58:12.690 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-15 08:58:12.874 [INF] CHDB: Compacting database file at /root/.lnd/data/graph/mainnet/wtclient.db
2023-11-15 08:58:12.893 [INF] CHDB: DB compaction of /root/.lnd/data/graph/mainnet/wtclient.db successful, 131072 -> 131072 bytes (gain=1.00x)
2023-11-15 08:58:12.894 [INF] CHDB: Swapping old DB file from /root/.lnd/data/graph/mainnet/temp-dont-use.db to /root/.lnd/data/graph/mainnet/wtclient.db
2023-11-15 08:58:12.897 [INF] CHDB: Compacting database file at /root/.lnd/data/watchtower/bitcoin/mainnet/watchtower.db
2023-11-15 08:58:12.906 [INF] CHDB: DB compaction of /root/.lnd/data/watchtower/bitcoin/mainnet/watchtower.db successful, 262144 -> 262144 bytes (gain=1.00x)
2023-11-15 08:58:12.907 [INF] CHDB: Swapping old DB file from /root/.lnd/data/watchtower/bitcoin/mainnet/temp-dont-use.db to /root/.lnd/data/watchtower/bitcoin/mainnet/watchtower.db
2023-11-15 08:58:12.907 [INF] LTND: Creating local graph and channel state DB instances
2023-11-15 08:58:14.710 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-15 08:58:16.329 [INF] CHDB: Checking for schema update: latest_version=31, db_version=29
2023-11-15 08:58:16.329 [INF] CHDB: Performing database schema migration
2023-11-15 08:58:16.329 [INF] CHDB: Applying migration #31
2023-11-15 08:58:16.329 [INF] CHDB: Deleting top-level bucket: 737765657065722d6c6173742d7478 ...
2023-11-15 08:58:16.330 [INF] CHDB: Deleted top-level bucket: 737765657065722d6c6173742d7478
2023-11-15 08:58:16.331 [INF] CHDB: Checking for optional update: prune_revocation_log=false, db_version=empty
2023-11-15 08:58:16.333 [INF] LTND: Database(s) now open (time_to_open=27m14.341636575s)!
2023-11-15 08:58:16.333 [INF] LTND: We're not running within systemd or the service type is not 'notify'
2023-11-15 08:58:16.333 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2023-11-15 08:58:16.734 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
[initunlocklnd] Wallet and Unlock files are present... parsing wallet password and unlocking lnd
2023-11-15 08:58:18.620 [INF] LNWL: Opened wallet
2023-11-15 08:58:18.729 [INF] CHRE: Primary chain is set to: bitcoin
{}[initunlocklnd] Preparing to start Loop
./docker-initunlocklnd.sh: line 94: [: missing `]'
2023-11-15 08:58:18.770 [INF] LNWL: Started listening for bitcoind block notifications via ZMQ on 172.24.0.8:28332
2023-11-15 08:58:18.771 [INF] CHRE: Initializing bitcoind backed fee estimator in CONSERVATIVE mode
2023-11-15 08:58:18.770 [INF] LNWL: Started listening for bitcoind transaction notifications via ZMQ on 172.24.0.8:28333
2023-11-15 08:58:20.064 [INF] LNWL: The wallet has been unlocked without a time limit
2023-11-15 08:58:20.072 [INF] CHRE: LightningWallet opened
2023-11-15 08:58:20.099 [INF] SRVR: Onion services are accessible via Tor! NOTE: Traffic to clearnet services is not routed via Tor.
2023-11-15 08:58:20.516 [INF] HSWC: Cleaning circuits from disk for closed channels
2023-11-15 08:58:20.633 [INF] HSWC: Finished cleaning: num_closed_channel=477, num_circuits=0, num_keystone=0
2023-11-15 08:58:20.633 [INF] HSWC: Restoring in-memory circuit state from disk
2023-11-15 08:58:20.651 [INF] HSWC: Payment circuits loaded: num_pending=10, num_open=10
```

btw @rockstardev do you have an idea how to speed up that restart? This is not related to v0.17 and has been the same before as well. We are compacting the db once per week, but > 25 minutes per restart is kinda rough for a production instance. Hints appreciated  /cc @alexbosworth

fyi `htop` looks mostly idle during compacting.

grafik

**Comment by alexbosworth** [comment]
seems like the db is large so compaction requires copying it which requires time?

**Comment by dennisreimann** [comment]
@alexbosworth Thanks for replying quickly! The channel.db file is arount 14 GB, when I `cp` it that takes about 5min — though that's also a chunk, it cannot be the majority of that time. Any hints on how we can improve that on our end?

**Comment by alexbosworth** [comment]
reduce channel db size by:

- clean out payments that failed
- turn on garbage collection for invoices that were canceled
- close and reopen channels that have a high number of updates

**Comment by NicolasDorier** [comment]
Updated, doesn't seem to have any issue.

**Comment by dennisreimann** [comment]
Thanks @alexbosworth, we're getting there :)

Posting my findings for people interested and following along: Added a [custom lnd.conf](https://docs.btcpayserver.org/FAQ/LightningNetwork/#how-to-edit-lndconf) containing these options:

```yml
version: "3"
services:
  lnd_bitcoin:
    environment:
      LND_EXTRA_ARGS: |
        # Optimizations, see https://docs.lightning.engineering/lightning-network-tools/lnd/lnd.conf
        db.prune-revocation=true
        ignore-historical-gossip-filters=true
        # Compact on every start
        db.bolt.auto-compact-min-age=0
        # Delete canceled invoices
        gc-canceled-invoices-on-startup=true
        gc-canceled-invoices-on-the-fly=true
        # Startup improvements
        sync-freelist=true
        stagger-initial-reconnect=true
        # Avoid auto force closes
        payments-expiration-grace-period=2m
        
required:
  - "bitcoin-lnd"
  - "opt-lnd-autocompact"
```

Applying the prune revocations migration ( `db.prune-revocation=true`) didn't help much in our case, but garbage collecting failed/canceled payments brought down the size from `15.5 GB` to `10.8 GB`, so that was notable.

```
2023-11-16 09:33:37.823 [INF] LTND: Version: 0.17.1-beta commit=basedon-v0.17.1-beta-fresh-btcpay, build=production, logging=default, debuglevel=info
2023-11-16 09:33:37.824 [INF] LTND: Active chain: Bitcoin (network=mainnet)
2023-11-16 09:33:37.826 [INF] RPCS: RPC server listening on 127.0.0.1:10009
2023-11-16 09:33:37.826 [INF] RPCS: RPC server listening on 127.0.0.1:10008
2023-11-16 09:33:37.826 [INF] RPCS: RPC server listening on 172.25.0.9:10009
2023-11-16 09:33:37.844 [INF] RPCS: gRPC proxy started at 172.25.0.9:8080
2023-11-16 09:33:37.858 [INF] LTND: Opening the main database, this might take a few minutes...
2023-11-16 09:33:37.863 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=true
2023-11-16 09:33:37.864 [INF] CHDB: Compacting database file at /root/.lnd/data/graph/mainnet/channel.db

2023-11-16 09:46:34.785 [INF] CHDB: DB compaction of /root/.lnd/data/graph/mainnet/channel.db successful, 15500472320 -> 10880368640 bytes (gain=1.42x)
2023-11-16 09:46:34.787 [INF] CHDB: Swapping old DB file from /root/.lnd/data/graph/mainnet/temp-dont-use.db to /root/.lnd/data/graph/mainnet/channel.db
2023-11-16 09:46:36.345 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-16 09:46:36.458 [INF] CHDB: Compacting database file at /root/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2023-11-16 09:46:36.485 [INF] CHDB: DB compaction of /root/.lnd/data/chain/bitcoin/mainnet/macaroons.db successful, 32768 -> 32768 bytes (gain=1.00x)
2023-11-16 09:46:36.486 [INF] CHDB: Swapping old DB file from /root/.lnd/data/chain/bitcoin/mainnet/temp-dont-use.db to /root/.lnd/data/chain/bitcoin/mainnet/macaroons.db
2023-11-16 09:46:36.486 [INF] CHDB: Compacting database file at /root/.lnd/data/graph/mainnet/sphinxreplay.db

2023-11-16 09:52:24.108 [INF] CHDB: DB compaction of /root/.lnd/data/graph/mainnet/sphinxreplay.db successful, 3463454720 -> 3430506496 bytes (gain=1.01x)
2023-11-16 09:52:24.110 [INF] CHDB: Swapping old DB file from /root/.lnd/data/graph/mainnet/temp-dont-use.db to /root/.lnd/data/graph/mainnet/sphinxreplay.db
2023-11-16 09:52:24.195 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-16 09:52:24.649 [INF] CHDB: Compacting database file at /root/.lnd/data/graph/mainnet/wtclient.db
2023-11-16 09:52:26.218 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-16 09:52:27.743 [INF] CHDB: DB compaction of /root/.lnd/data/graph/mainnet/wtclient.db successful, 73826304 -> 33570816 bytes (gain=2.20x)
2023-11-16 09:52:27.744 [INF] CHDB: Swapping old DB file from /root/.lnd/data/graph/mainnet/temp-dont-use.db to /root/.lnd/data/graph/mainnet/wtclient.db
2023-11-16 09:52:27.756 [INF] CHDB: Compacting database file at /root/.lnd/data/watchtower/bitcoin/mainnet/watchtower.db
2023-11-16 09:52:27.769 [INF] CHDB: DB compaction of /root/.lnd/data/watchtower/bitcoin/mainnet/watchtower.db successful, 262144 -> 262144 bytes (gain=1.00x)
2023-11-16 09:52:27.770 [INF] CHDB: Swapping old DB file from /root/.lnd/data/watchtower/bitcoin/mainnet/temp-dont-use.db to /root/.lnd/data/watchtower/bitcoin/mainnet/watchtower.db
2023-11-16 09:52:27.770 [INF] LTND: Creating local graph and channel state DB instances
2023-11-16 09:52:28.239 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-16 09:52:30.260 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: waiting to start, RPC services not available
[initunlocklnd] Still waiting on LND, got response for wallet status: {"state":"WAITING_TO_START"} ... waiting another 2 seconds...
2023-11-16 09:52:31.493 [INF] CHDB: Checking for schema update: latest_version=31, db_version=31
2023-11-16 09:52:31.493 [INF] CHDB: Checking for optional update: prune_revocation_log=true, db_version=0: prune revocation log
2023-11-16 09:52:31.495 [INF] LTND: Database(s) now open (time_to_open=18m53.631853709s)!
2023-11-16 09:52:31.496 [INF] LTND: We're not running within systemd or the service type is not 'notify'
2023-11-16 09:52:31.496 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.
2023-11-16 09:52:32.283 [ERR] RPCS: [/lnrpc.Lightning/GetInfo]: wallet locked, unlock it to enable full RPC access
[initunlocklnd] Wallet and Unlock files are present... parsing wallet password and unlocking lnd
2023-11-16 09:52:34.221 [INF] LNWL: Opened wallet
```

Does [chantools](https://github.com/lightninglabs/chantools#command-overview) offer even more ways of optimizations or is e.g. `deletepayments` already covered by the above settings? /cc @guggero 

Sorry to bother you with these questions, my goal is to ship as much of those optimizations and tools as default with the BTCPay Server setup.

**Review by dennisreimann — APPROVED** [review]
Working for us, rest of what I posted is unrelated to the updates and just fyi.

**Comment by alexbosworth** [comment]
Compact on every start may be overkill, compacting immediately wouldn't have any impact except to slow down startup

Definitely under no circumstances turn on sync-freelist

I don't think adjusting payments expiry grace period is a great idea either

**Comment by dennisreimann** [comment]
@alexbosworth Gotcha, adjusted it — thanks for the feedback!

**Comment by rockstardev** [comment]
Tested on my servers and talked with few more people, no blockers, merging this tomorrow if no NACKs.

**Comment by rockstardev** [comment]
If you're reading this, go straight for 0.17.2-beta -> https://github.com/btcpayserver/btcpayserver-docker/pull/846

**Pull request merged**
