### PR TITLE
Added support for Cheat Mode

### PR DESCRIPTION
**Pull request by woutersamaey**

### CODE REVIEW

**Comment by woutersamaey** [comment]
@dennisreimann and @NicolasDorier for your review.

**Review by dennisreimann — APPROVED** [review]

**Comment by NicolasDorier** [comment]
I think we shouldn't expose it and document it.
What you can do instead is to use a custom fragment.

**Comment by woutersamaey** [comment]
Erm? How does obscurity help anyone?

**Comment by woutersamaey** [comment]
We discussed and agreed this is not a feature for the general public.

**Comment by NicolasDorier** [comment]
https://github.com/btcpayserver/btcpayserver-docker#how-can-i-customize-the-generated-docker-compose-file

**Pull request closed without merging**
