### PR TITLE
bump clighting rest

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Reverting @pavlenex  reported it does not work.

**Comment by NicolasDorier** [comment]
ping @saubyk

ping @pavlenex 

```
Error: connect ECONNREFUSED /root/.lightning
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on LightningClient instance at:
    at Socket.<anonymous> (/usr/src/app/lightning-client-js.js:71:23)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning'
}
```

I reverted to 21 for now please let us know pav

**Comment by pavlenex** [comment]
Testing this on several servers atm, trying to replicate. Will let you know.

**Comment by pavlenex** [comment]
So tested on 3 servers.

1. RPI 4 c-lightning container keeps crashing on both `c-lightning-rest:0.2.2` and `c-lightning-rest:0.2.1` regardless. Giving the same error:
```
}
Reading config file
Reading config file
--- Starting the cl-rest server ---
Reading SSL cert and key
Reading rootkey for macaroon
--- cl-rest api server is ready and listening on port: 3001 ---
--- cl-rest doc server is ready and listening on port: 4001 ---
Lightning client connection error Error: connect ECONNREFUSED /root/.lightning
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning'
}
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED /root/.lightning
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
Emitted 'error' event on LightningClient instance at:
    at Socket.<anonymous> (/usr/src/app/lightning-client-js.js:71:23)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/root/.lightning'
}
```
2. Tried with LND 0.8.2 on a VPS and can't replicate.
3. Tried on c-lighting VPS with can't replicate.

This leads me to think this is isolated issue possibility related to port opening? 
I have 80, 443 and 9735 opened.

**Comment by saubyk** [comment]
This issue is occuring because c-lightning-REST is not able to talk to c-lightning.

Basically c-lightning-REST should be able to read `/root/.lightning` folder to be able to communicate with c-lightning

**Comment by NicolasDorier** [comment]
we did not changed anything about that... I guess something funky in c-lightning on new installs.

**Comment by NicolasDorier** [comment]
Will revert the revert. @pavlenex you should report on c-ligthning repo then.

**Pull request merged**
