### PR TITLE
chore: update to dash 19.0.0

### PR DESCRIPTION
**Pull request by strophy**
Dash has updated to `v19.0.0` and a hard fork will occur sometime in the future. This PR updates the Docker build system to use this version. Please merge https://github.com/btcpayserver/dockerfile-deps/pull/61 first.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@strophy the images doesn't build https://app.circleci.com/pipelines/github/btcpayserver/dockerfile-deps/645 please fix it

**Comment by strophy** [comment]
@NicolasDorier this should fix it: https://github.com/btcpayserver/dockerfile-deps/pull/62

**Comment by astupidmoose** [comment]
Does this also fix the settings.json issue?

Error: Failed loading settings file:
- Unable to parse settings file /home/bitcoin/.dashcore/settings.json

https://github.com/btcpayserver/dockerfile-deps/pull/58#issuecomment-1405872093

**Comment by NicolasDorier** [comment]
@astupidmoose I fixing this one, deploying the new version now.

**Comment by astupidmoose** [comment]
Fixed and working. Thank you! 8 months of downtime finally up and running lololol

**Pull request merged**
