### PR TITLE
Added Support for Dash 0.14.0

### PR DESCRIPTION
**Pull request by asadaddy**
Please tell me why does the file "DockerComposeDefination.cs" crashed? I have commented the Exception "new NotImplementedException" and it works fine.

### CODE REVIEW

**Comment by astupidmoose** [comment]
Cc @snogcel

**Comment by NicolasDorier** [comment]
@asadaddy  because I commited something I should not have, sorry for that.

**Comment by NicolasDorier** [comment]
@asadaddy fixed on 7d2f588639f2a57a675d66144f86cb3c4fcf0e05

**Comment by NicolasDorier** [comment]
Anyway, the support for Dash 0.14.0 has not been added by @snogcel so this PR can't work.

**Comment by NicolasDorier** [comment]
Ok you pushed on https://github.com/btcpayserver/dockerfile-deps/pull/6 . Making the images.

**Comment by NicolasDorier** [comment]
The image Dash 0.14 has been published. @asadaddy @astupidmoose you can test with a running btcpay by changing the dash version of `vim $BTCPAY_DOCKER_COMPOSE`.

Let me know if nothing explode.

**Comment by NicolasDorier** [comment]
Please any one of you can test this? If I push the merge button and that somehow the image is fucked up, it will crash the install of everybody using Dash.

**Comment by snogcel** [comment]
Hey @NicolasDorier I'll make note of this and can test it out next week (traveling at the moment).

**Comment by astupidmoose** [comment]
> Please any one of you can test this? If I push the merge button and that somehow the image is fucked up, it will crash the install of everybody using Dash.

Exactly why I don't want to "test" it :P If I get time I can try to launch a new instance, but won't do it on my production server lol

**Comment by NicolasDorier** [comment]
@snogcel any luck testing it?

**Comment by astupidmoose** [comment]
I've had 0.14.0 based on this update running for a week, I've had payments coming in since then, so I'm assuming its running but have no idea any of the specs behind it.

**Comment by snogcel** [comment]
Sorry for the delay @NicolasDorier I've mostly cleared out my backlog and should have time to test this on Monday / Tuesday

**Comment by Kukks** [comment]
#151 is taking over this one

**Pull request closed without merging**
