### PR TITLE
Bump Monero version and migrate to DNSBL

### PR DESCRIPTION
**Pull request by sethsimmons**

### CODE REVIEW

**Comment by wallopthecat** [comment]
this tag does not exist `     image: btcpayserver/monero:0.17.1.8`

**Comment by jooray** [comment]
This broke btcpay-update.sh

Pulling monerod (btcpayserver/monero:0.17.1.8)...
ERROR: manifest for btcpayserver/monero:0.17.1.8 not found: manifest unknown: manifest unknown

**Comment by sethsimmons** [comment]
I’ve updated https://github.com/btcpayserver/dockerfile-deps/blob/master/Monero/0.17.1.8/linuxamd64.Dockerfile, so I’m not sure if there is anything else I can do to get that image built via CI.

@NicolasDorier is there some other place that needs to be updated so the new tag is available in Docker Hub?

**Comment by sethsimmons** [comment]
Opened https://github.com/btcpayserver/btcpayserver-docker/issues/420

**Comment by NicolasDorier** [comment]
indeed fixed

**Pull request merged**
