### PR TITLE
chore: bump thunderhub

### PR DESCRIPTION
**Pull request by apotdevin**

### CODE REVIEW

**Review by Kukks — APPROVED** [review]
LGTM

@NicolasDorier  I am going to create a github actions CI to run the image builder script

**Comment by uhlhosting** [comment]
I bumped thunderhub to this version, together with lnd: 

resulted in:

```
2021-02-26 04:12:21 error [THUB]: Unable to connect to this node
2021-02-26 04:12:27 verbose [THUB]: Found cookie at path /data/.cookie
2021-02-26 04:12:27 verbose [THUB]: Refreshing cookie for next authentication
2021-02-26 04:12:27 error [THUB]: Unable to connect to this node
```

**Comment by uhlhosting** [comment]
After several attempts in my setup with LND is not working: 
updated also LND to 1.12.0.beta and with or without the update, simply updating Thunderhub will break the SSO usage and will result in above errors, in my setup the login page to thunderhub redirects back to btc when opened.

**Comment by apotdevin** [comment]
@uhlhosting hey, any more details you can provide? I am not able to reproduce this issue. It's been working for me for all previous versions

**Comment by uhlhosting** [comment]
New version released!

**Comment by apotdevin** [comment]
@uhlhosting docker image for the new version is not yet available, should be available soon

**Comment by NicolasDorier** [comment]
@apotdevin don't hesitate to bu me directly when I don't merge fast

**Comment by NicolasDorier** [comment]
I also bumped to .13

**Comment by NicolasDorier** [comment]
bumping to .15 actually

**Pull request merged**
