### PR TITLE
add in lnd auto pilot for all other lnd supporting coins and add in pruning options for all other coins

### LINKED ISSUE #40: Expand pruning to other crypto nodes
We need to allow pruning to other crypto nodes. Guessing we should add a key to the crypto definition file at this point? We should also duplicate the exisitng btc ones to have fragments starting with `btc-* ` to scale. :)

### PR DESCRIPTION
**Pull request by Kukks**
closes #40

### CODE REVIEW

**Comment by NicolasDorier** [comment]
@Kukks don't create separate fragment per coins. Just add stuff to `opt-lnd-autopilot`. If the image is not present, it will just be ignored.

**Comment by Kukks** [comment]
Are you sure that works? The last time I tried that it caused issues for when you didn't include the service. For example, having `opt-lnd-autopilot` handle both btc and ltc when you did not include ltc would cause the compose file to be invalid

**Comment by NicolasDorier** [comment]
@Kukks I might have fixed that since then... else we need to just ignore so it does not crash.

**Comment by Kukks** [comment]
Wouldn't having them separated be good in any case though? It allows users to be able to decide what level of pruning they want to achieve per coin along with the type of lightning integration?

**Comment by NicolasDorier** [comment]
@Kukks if the user wants its own rules, he can use custom fragments.
I think you should have only 1. If they want more complex rule per crypto, it will be very easy for them to copy part of what they want and make their own fragments.

**Comment by NicolasDorier** [comment]
Different crypto have different block time and size, so in theory we should adjust the numbers... but well, since most altcoins are unused it won't matter too much I think.

**Pull request merged**
