### PR TITLE
Fixed git -c command for CentOS Linux

### PR DESCRIPTION
**Pull request by iam1412**
Fixed git -C to git -c for CentOS Linux Command

### CODE REVIEW

**Comment by wakiyamap** [comment]
CentOS Linux 7
```
git version 1.8.3.1
cat /etc/os-release
NAME="CentOS Linux"
```


CentOS Stream 8
```
git version 2.31.1
cat /etc/os-release
NAME="CentOS Stream"
```
image

CentOS Stream 9
```
git version 2.31.1
cat /etc/os-release
NAME="CentOS Stream"
```
image

I summarized the display of CentOS at hand.
I hope it's a useful reference.

**Comment by iam1412** [comment]
> 

Thank you for test on CentOS8 and 9

I testing on CentOS 7

**Comment by wakiyamap** [comment]
Personally, I recommend migrating to AlmaLinux or Rocky Linux.
Building git yourself is a hassle.

**Comment by iam1412** [comment]
will try.

Thank you.

**Pull request closed without merging**
