### PR TITLE
Add GRS Clightning + spark + charge

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I think you should leave out spark. They should have their own fork.

**Comment by NicolasDorier** [comment]
Never use `latest` the update process does not attempt to fetch the latest images so it can be fast.

**Comment by Kukks** [comment]
Yeah I know, we were just testing :)
ᐧ

**Comment by Kukks** [comment]
@NicolasDorier  Ready to merge

**Comment by NicolasDorier** [comment]
fix conflict

**Comment by NicolasDorier** [comment]
done?

**Comment by NicolasDorier** [comment]
have you tried a new deployment with it?

**Comment by Kukks** [comment]
Yes, it's good to go. :)
ᐧ

**Comment by NicolasDorier** [comment]
did you tried it yourself? because a `{{ end }}` is missing.

**Comment by Kukks** [comment]
Hmm that should have been fixed, let me force push my local

**Comment by Kukks** [comment]
Yup it's there now

**Comment by Kukks** [comment]
It's already deployed with the latest @ https://grs.kukks.org
ᐧ

**Comment by Kukks** [comment]
It is correct, i deployed it again

**Pull request merged**
