### PR TITLE
Bumping to v0.12.1-beta container and enabling Loop usage

### PR DESCRIPTION
**Pull request by rockstardev**
Supersedes #439 

Getting ready for https://www.youtube.com/watch?v=u2VCOrq5Nr4

https://user-images.githubusercontent.com/5191402/111927239-0e939f00-8a7e-11eb-991c-7c0901977cd4.mp4

### CODE REVIEW

**Review by jaonoctus — APPROVED** [review]
lgtm.

awesome work!

**Comment by NicolasDorier** [comment]
@pavlenex @britttttk anybody willing to test loop?

**Comment by britttttk** [comment]
sure I can try it 🚀 @NicolasDorier

**Comment by pavlenex** [comment]
@britttttk Did we test this one? Would be good to get it merged.

There's a minor conflict in readme @rockstardev 📖 😺

**Comment by rockstardev** [comment]
We a problem with legacy LND containers because they didn't have lnd_bitcoin as supported name in tls certificate. So don't merge this PR, I'll address this with new commits and then move PR back into "Ready to merge" state.

`loopd exited with an error: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for 9c810cdc64ae, localhost, unix, unixpacket, bufconn, not lnd_bitcoin"`

**Comment by rockstardev** [comment]
@britttttk saved the day with testing, this version should work without problems or any manual intervention from people.

Notes:
- I've left tool for deleting TLS, but it's not needed
- Published new version of LND container, since Loop would occasionally fail with error: `Runtime error in daemon, shutting down: rpc error: code = Unknown desc = chain notifier RPC is still in the process of starting`

**Comment by rockstardev** [comment]
@britttttk saved the day with testing, this version should work without problems or any manual intervention from people.

Notes:
- I've left tool for deleting TLS, but it's not needed
- Published new version of LND container, since Loop would occasionally fail with error: `Runtime error in daemon, shutting down: rpc error: code = Unknown desc = chain notifier RPC is still in the process of starting`

**Comment by NicolasDorier** [comment]
Should the certificate script appear in the doc? If you think it's ready then merge

**Comment by rockstardev** [comment]
@NicolasDorier no, script is there just for reference... but if you find it too confusing, you can delete it. Also merge only after we have one more tACK, just to make sure.

**Comment by jaonoctus** [comment]
How can I test it?

**Comment by NicolasDorier** [comment]
@rockstardev I mean `lnd_delete_tls.sh`, what is it fixing? what is the purpose?
Also did you thought about `git update-index --chmod=+x` the file?

**Comment by rockstardev** [comment]
@NicolasDorier it's not fixing anything right now. The purpose is that people have it in case they want to reset tls.cert.

I already did `git update-index --chmod=+x lnd_delete_tls.sh` on the file.

**Comment by rockstardev** [comment]
> How can I test it?

@jaonoctus if you have BtcPayServer installed using this `btcpayserver-docker` repository ssh into instance and run these two commands:

```
git checkout feat/lnd-0.12.1-beta-withloop
. btcpay-setup.sh -i
```

After server starts you should be able to use Loop:

btcpayserver loop

**Review by jaonoctus — APPROVED** [review]
tACK

**Comment by jaonoctus** [comment]
> git checkout feat/lnd-0.12.1-beta-withloop
> . btcpay-setup.sh -i

After I checkout back to the `master` branch, I got `unable to open databases: unable to open local channeldb: channel db cannot revert to prior version`.

So for everyone who is going to test, pay attention to this.

**Comment by NicolasDorier** [comment]
@jaonoctus you can update now

**Comment by rockstardev** [comment]
One note here - if you update and Loop is still not working for you do: `docker logs btcpayserver_lnd_bitcoin`

If you're getting `[lnd_unlock] WARNING: UNLOCK FILE DOESN'T EXIST! MIGRATE LEGACY INSTALLATION TO NEW VERSION ASAP` in logs that means you've deployed BtcPayServer a while ago and the version of LND container you have isn't able to work with Loop - would require manual interventions - like complete regeneration of macaroons.

You could migrate LND container using instructions I've provided last year when we added seed backup. But since migration to LightningLabs provided containers is coming in next month-two, I would encourage you to wait for if you don't want to migrate multiple times (and are particularly attached to your channels).

**Pull request merged**
