### PR TITLE
LND: Add watchtower fragment

### PR DESCRIPTION
**Pull request by dennisreimann**
Adds optional support for running a [watchtower](https://github.com/lightningnetwork/lnd/blob/master/docs/watchtower.md#configuring-a-watchtower).

### CODE REVIEW

**Review by rockstardev — CHANGES_REQUESTED** [review]
I have bumped our LND to have watchtower tags based on changes you suggested:
https://hub.docker.com/r/btcpayserver/lnd/tags

So now all that is needed to be done is modify https://github.com/btcpayserver/btcpayserver-docker/blob/master/docker-compose-generator/docker-fragments/bitcoin-lnd.yml

To use different image:
`image: btcpayserver/lnd:v0.16.4-beta-1`

**Comment by dennisreimann** [comment]
Yup, can confirm it workls as expected now :)

```bash
Pulling lnd_bitcoin (btcpayserver/lnd:v0.16.4-beta-1)...
v0.16.4-beta-1: Pulling from btcpayserver/lnd
Status: Downloaded newer image for btcpayserver/lnd:v0.16.4-beta-1

[...]

# ./bitcoin-lncli.sh --version
lncli version 0.16.4-beta commit=basedon-v0.16.4-beta-1-fresh-btcpay

# ./bitcoin-lncli.sh version
{
    "lncli": {
        "commit": "basedon-v0.16.4-beta-1-fresh-btcpay",
        "commit_hash": "f1c273911899ab2d4e90b9fdbf3aa833e57b3393",
        "version": "0.16.4-beta",
        "app_major": 0,
        "app_minor": 16,
        "app_patch": 4,
        "app_pre_release": "beta",
        "build_tags": [
            "signrpc",
            "walletrpc",
            "chainrpc",
            "invoicesrpc",
            "routerrpc",
            "watchtowerrpc"
        ],
        "go_version": "go1.20.3"
    },
    "lnd": {
        "commit": "basedon-v0.16.4-beta-1-fresh-btcpay",
        "commit_hash": "f1c273911899ab2d4e90b9fdbf3aa833e57b3393",
        "version": "0.16.4-beta",
        "app_major": 0,
        "app_minor": 16,
        "app_patch": 4,
        "app_pre_release": "beta",
        "build_tags": [
            "signrpc",
            "walletrpc",
            "chainrpc",
            "invoicesrpc",
            "routerrpc",
            "watchtowerrpc"
        ],
        "go_version": "go1.20.3"
    }
}

# ./bitcoin-lncli.sh tower
NAME:
   lncli tower - Interact with the watchtower.

USAGE:
   lncli tower command [command options] [arguments...]

COMMANDS:
   info  Returns basic information related to the active watchtower.
```

**Review by rockstardev — APPROVED** [review]
Looks great!

**Comment by petzsch** [comment]
A [user on telegram](https://t.me/btcpayserver/62737) is stuggeling with getting the fragment working with tor connectivity.
Can we make watchtower over tor useable by default?

**Comment by dennisreimann** [comment]
We haven't integrated the LND version with the watchtower RPC in our Docker deployment yet, I just opened btcpayserver/btcpayserver-docker#833, which will make it accessible.

**Pull request merged**
