### PR TITLE
feat: add arm32v7 image

### PR DESCRIPTION
**Pull request by apotdevin**
-   Add arm32v7 docker image

### CODE REVIEW

**Comment by Kukks** [comment]
Can you rebase?

**Comment by NicolasDorier** [comment]
why did you replaced the `*` by `-` in README? can you remove this? Also do you plan to add arm64v8 soon?

**Comment by apotdevin** [comment]
> why did you replaced the `*` by `-` in README? can you remove this? Also do you plan to add arm64v8 soon?

Didn't see that file get in sorry for that. Will remove. As soon as I can get my hands on an arm64 device or test it somehow will add the respective image

**Comment by NicolasDorier** [comment]
@apotdevin I have a arm64 device I can test when you can

**Comment by NicolasDorier** [comment]
Also advice use variant properly:

This is your manifest
```
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1786,
         "digest": "sha256:dcc5aae7200aa36767ebdb8345a8cf50e5d1823a341ebc2fb1c3a3ee5949f949",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1786,
         "digest": "sha256:eb31f272f61ca4d245ca156a193b1ed225ccb0f509b31c2db6784e863194dffb",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
```

It should be
```
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2000,
         "digest": "sha256:2c31df06fbe49c39a97141c850c72e23fd34f90a034591010987a96983829344",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      }
```

**Comment by NicolasDorier** [comment]
You can inspire yourself from how we publish btcpayserver https://github.com/btcpayserver/btcpayserver/blob/master/.circleci/config.yml#L98

**Comment by apotdevin** [comment]
> @apotdevin I have a arm64 device I can test when you can

Would be perfect, will finish some things up, push an arm64 image and contact you on MM. Thanks for the advice, will add it in 👍

**Pull request merged**
