### PR TITLE
Bump Monero to v0.17.2.3

### PR DESCRIPTION
**Pull request by sethsimmons**

### CODE REVIEW

**Comment by sethsimmons** [comment]
Please wait to merge this until after merging https://github.com/btcpayserver/dockerfile-deps/pull/32.

**Comment by sethsimmons** [comment]
Ping @Kukks.

**Comment by sethsimmons** [comment]
@Kukks Anything else needed from me? This fixes a somewhat serious wallet issue, so would be good to get it patched ASAP.

**Review by Kukks — APPROVED** [review]

**Comment by sethsimmons** [comment]
Thanks!

**Pull request merged**
