### PR TITLE
BTG Lnd docker fragment

### PR DESCRIPTION
**Pull request by Vutov**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
can you provide `bgold-lncli.sh` utility ? Also do not forget to `git update-index --chmod+x ./bgold-lncli.sh` after having `git add bgold-lncli.sh`

**Comment by NicolasDorier** [comment]
Also fix indentation please.

**Comment by Vutov** [comment]
Sure thing.

**Comment by Vutov** [comment]
Done, the indentation was strange in the whole file, so I took the liberty to ctr+k ctr+d it :)

**Pull request merged**
